name: Feature Request
description: Suggest an improvement to the reference server
labels: ['enhancement']
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A concise description of the proposed improvement.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this needed? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposed-implementation
    attributes:
      label: Proposed Implementation
      description: How would you approach implementing this?
